# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Spring Endurance + Wellness
header-title: spring endurance + wellness
email: hello@springendurance.com
author: Michael Curtis
description: Helping athletes find joy through purposeful training.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://springendurance.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assests/images/main-logo.png
social:
  name: Michael Curtis
  links:
    - https://instagram.com/michaelcurtistri
    - https://www.facebook.com/michael.mcneil.5855594
    - https://www.facebook.com/springendurancewellness
    - https://instagram.com/springendurance

include: ["_forms"]

google-analytics: UA-147475824-1
snipcart_key: "YTc4ODM4MWEtODUyMS00ZWQxLWIwMWUtMmNkNzc2YzBkMjRjNjM3MDc3ODUxODQxMDkxMDIw"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  products:
    output: true
    permalink: /shop/:name
  services:
    output: true
  pages:
    output: true
    permalink: /:permalink/

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: product
